[package]
name = "hlc-rs"
version = "0.1.0"
authors = ["Toby Sullivan <tobyjsullivan@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
hyper = "0.12.21"
lazy_static = "1.2.0"
regex = "1.1.0"
serde = "1.0.84"
serde_derive = "1.0.85"
serde_json = "1.0.36"
url = "1.7.2"
